version: '3'
services:
  src:
    build:
      context: ./src
      dockerfile: DockerFile
    command: npm i
    ports:
      - 8080:8000
    depends_on:
      - db
    environment:
      MONGODB_DATABASE: Employee
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: Employee
      ME_CONFIG_BASICAUTH_PASSWORD: Employee
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Employee
    links:
      - db

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
    - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Employee
