version: '3.1'
services:
  api:
    build:
      context: ./api/src
      dockerfile: DockerFile
    command: npm i
    ports:
      - 8080:8000
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
    - ./data:/data/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: employee
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: employee
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://employee:example@mongo:27017/
      ME_CONFIG_MONGODB_SERVER: mongo
  front_end:
    build:
      context: ./front_end/src
      dockerfile: DockerFile
    command: npm i
    ports:
      - 3000:3001
    depends_on:
      - mongo
      - api
